# Generated by Django 5.1.3 on 2024-12-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeedetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='salary_credited',
            field=models.BooleanField(default=False),
        ),
    ]
