# Generated by Django 5.1.3 on 2024-12-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeesalary_salary_credited'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydetail',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salarydetail',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
