# Generated by Django 5.1.3 on 2024-12-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_paymentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='final_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
