# Generated by Django 5.1.3 on 2024-12-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_paymentschedule_final_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
