# Generated by Django 5.1.3 on 2024-12-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_paymentschedule_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentschedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentschedule',
            name='final_salary',
        ),
        migrations.RemoveField(
            model_name='paymentschedule',
            name='payment_status',
        ),
    ]
