# Generated by Django 5.1.3 on 2024-12-19 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_paymentschedule_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
