# Generated by Django 5.1.3 on 2024-12-19 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_remove_paymentschedule_deductions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePaymentDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeedetail')),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeePaymentSchedule',
        ),
    ]
